<!-- Zentient Endpoints Messaging Project File -->
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<!-- Analyzer test projects should usually target the same netstandard as the analyzer -->
		<TargetFrameworks>net8.0;net9.0</TargetFrameworks>

		<RootNamespace>Zentient.Endpoints.Messaging</RootNamespace>
		<Description>Messaging transport support (MassTransit, etc.) for Zentient.Endpoints.</Description>
		<IsPackable>true</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<!--<ProjectReference Include="../Zentient.Results/src/Results/Zentient.Results.csproj" />-->
		<PackageReference Include="System.Collections.Immutable" Version="9.0.6" PrivateAssets="all" />
		<PackageReference Include="Zentient.Results" Version="0.4.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="../Zentient.Endpoints/Zentient.Endpoints.csproj" />
	</ItemGroup>

</Project>
