<!-- Zentient Endpoints gRPC Project File -->
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<!-- Analyzer test projects should usually target the same netstandard as the analyzer -->
		<TargetFrameworks>net8.0;net9.0</TargetFrameworks>

		<RootNamespace>Zentient.Endpoints.Grpc</RootNamespace>
		<Description>gRPC integration for Zentient.Endpoints.</Description>
		<NoWarn>NU1605</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<!--<ProjectReference Include="../Zentient.Results/src/Results/Zentient.Results.csproj" />-->
		<PackageReference Include="System.Collections.Immutable" Version="9.0.0" PrivateAssets="all" />
		<PackageReference Include="Zentient.Results" Version="0.4.2" />
		<PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.6" Condition="'$(TargetFramework)' == 'net8.0'" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="[9.0.0,)" Condition="'$(TargetFramework)' == 'net9.0'" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="../Zentient.Endpoints/Zentient.Endpoints.csproj" />
	</ItemGroup>

</Project>
