<!-- Zentient Endpoints Core Project File -->
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<!-- Analyzer test projects should usually target the same netstandard as the analyzer -->
		<TargetFrameworks>net8.0;net9.0</TargetFrameworks>

		<RootNamespace>Zentient.Endpoints</RootNamespace>
		<IsPackable>true</IsPackable>
		<Description>Core abstractions and utilities for unifying result handling across transport protocols (HTTP, gRPC, Messaging) using Zentient.Results.</Description>
		<AssemblyOriginatorKeyFile>..\..\Zentient.snk</AssemblyOriginatorKeyFile>
		<PackageId>Zentient.Endpoints</PackageId>
		<PackageTags>Zentient;Endpoints;Results;Outcomes;Abstractions;Utilities;HTTP;gRPC;Messaging</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<None Include="Zentient.Endpoints.Http.Tests.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Zentient.Results" Version="0.4.4" />
	</ItemGroup>

</Project>
