<!-- Zentient Endpoints Tests Project File -->
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<!-- Analyzer test projects should usually target the same netstandard as the analyzer -->
		<TargetFrameworks>net8.0;net9.0</TargetFrameworks>

		<RootNamespace>Zentient.Endpoints.Tests</RootNamespace>
		<IsTestProject>true</IsTestProject>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<!--<ProjectReference Include="..\Zentient.Results\Src\Results\Zentient.Results.csproj" />-->
		<PackageReference Include="System.Collections.Immutable" Version="9.0.6" PrivateAssets="all" />
		<PackageReference Include="Zentient.Results" Version="[0.4.4, 5.0.0)" />
		<PackageReference Include="FluentAssertions" Version="8.3.0" />
		<PackageReference Include="Microsoft.Extensions.Options.Validation" Version="8.0.0-preview.5.23308.3" />
		<PackageReference Include="Moq" Version="4.20.72" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
		<PackageReference Include="xunit" Version="2.9.3" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Zentient.Endpoints.Http\Zentient.Endpoints.Http.csproj" />
		<ProjectReference Include="..\..\src\Zentient.Endpoints.Tests.Common\Zentient.Endpoints.Tests.Common.csproj" />
		<ProjectReference Include="..\..\src\Zentient.Endpoints\Zentient.Endpoints.csproj" />
	</ItemGroup>
</Project>
