      - name: 📁 Define Paths for Debugging
        run: |
          # Define variables for immediate use within this step
          REPO_ROOT="$GITHUB_WORKSPACE"
          MAIN_SOLUTION_PATH="$GITHUB_WORKSPACE/$SOLUTION_FILE_NAME"
          SRC_DIR="$GITHUB_WORKSPACE/Src"
          TESTS_DIR="$GITHUB_WORKSPACE/Tests"

          # Export them to be available for subsequent steps
          echo "REPO_ROOT=$REPO_ROOT" >> $GITHUB_ENV
          echo "MAIN_SOLUTION_PATH=$MAIN_SOLUTION_PATH" >> $GITHUB_ENV
          echo "SRC_DIR=$SRC_DIR" >> $GITHUB_ENV
          echo "TESTS_DIR=$TESTS_DIR" >> $GITHUB_ENV

          echo "--- Current Working Directory ---"
          pwd
          echo "--- Content of GITHUB_WORKSPACE ---"
          ls -F "$GITHUB_WORKSPACE"
          echo "--- Content of SRC_DIR ---"
          # Now these commands will correctly use the defined variables
          ls -F "${SRC_DIR}" || echo "SRC_DIR does not exist or is empty, despite being listed in GITHUB_WORKSPACE."
          echo "--- Content of TESTS_DIR ---"
          ls -F "${TESTS_DIR}" || echo "TESTS_DIR does not exist or is empty, despite being listed in GITHUB_WORKSPACE."

      - name: 🧪 Validate Structure for Debugging
        run: |
          echo "🗂 Validating paths..."
          # These will now correctly use the environment variables set in the previous step
          test -f "$MAIN_SOLUTION_PATH" || (echo "❌ Missing solution file: $MAIN_SOLUTION_PATH" && exit 1)
          test -d "$SRC_DIR" || echo "⚠️ Missing source dir: $SRC_DIR - This might be the cause of project file errors!"
          test -d "$TESTS_DIR" || echo "⚠️ Missing test dir: $TESTS_DIR - This might be the cause of project file errors!"
          echo "Validation complete."
